"""PDF report generation using ReportLab."""
import io
import base64
from datetime import datetime

from app.utils.logger import logger

# Try to import reportlab — gracefully degrade if not installed
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    logger.warning("reportlab not installed — PDF report generation disabled")


def generate_pdf_report(prediction_data: dict, image_base64: str | None = None) -> bytes:
    """
    Generate a PDF report from prediction results.

    Args:
        prediction_data: Full prediction response dict
        image_base64: Optional base64-encoded original image

    Returns:
        PDF file contents as bytes
    """
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("reportlab is not installed. Run: pip install reportlab")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=18,
        textColor=HexColor("#0ea5e9"),
        spaceAfter=12,
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=9,
        textColor=HexColor("#ef4444"),
        spaceBefore=6,
        spaceAfter=12,
        borderWidth=1,
        borderColor=HexColor("#ef4444"),
        borderPadding=6,
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=HexColor("#0ea5e9"),
        spaceBefore=12,
        spaceAfter=6,
    )

    elements = []

    # 1. Title
    elements.append(Paragraph("Medical Image Analysis Report", title_style))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    elements.append(Spacer(1, 6 * mm))

    # 2. Disclaimer
    elements.append(Paragraph(
        "<b>⚠ DISCLAIMER:</b> This report is generated by an AI system for educational purposes only. "
        "It does NOT constitute a medical diagnosis. Always consult a qualified healthcare professional.",
        disclaimer_style,
    ))
    elements.append(Spacer(1, 4 * mm))

    # 3. Uploaded Image
    if image_base64:
        try:
            # Strip the data URI prefix if present
            if "," in image_base64:
                image_base64 = image_base64.split(",", 1)[1]
            img_bytes = base64.b64decode(image_base64)
            img_buffer = io.BytesIO(img_bytes)
            elements.append(Paragraph("Uploaded Image", heading_style))
            elements.append(RLImage(img_buffer, width=120 * mm, height=90 * mm, kind="proportional"))
            elements.append(Spacer(1, 4 * mm))
        except Exception as e:
            logger.warning(f"Could not embed image in PDF: {e}")

    # 4. Detected Image Type
    image_type = prediction_data.get("image_type", {})
    if image_type:
        elements.append(Paragraph("Detected Image Type", heading_style))
        elements.append(Paragraph(
            f"Type: <b>{image_type.get('detected', 'Unknown').upper()}</b> "
            f"(Confidence: {image_type.get('confidence', 0) * 100:.1f}%)",
            styles["Normal"],
        ))
        elements.append(Spacer(1, 4 * mm))

    # 5. Prediction Results Table
    predictions = prediction_data.get("predictions", [])
    if predictions:
        elements.append(Paragraph("Prediction Results", heading_style))

        table_data = [["Disease", "Probability", "Risk Level"]]
        for pred in predictions:
            prob = f"{pred['probability'] * 100:.1f}%"
            table_data.append([pred["disease"], prob, pred["status"].replace("_", " ").title()])

        table = Table(table_data, colWidths=[80 * mm, 40 * mm, 40 * mm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#f1f5f9")),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#334155")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#f8fafc"), HexColor("#e2e8f0")]),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 4 * mm))

    # 6. Top Prediction Highlight
    top = prediction_data.get("top_prediction", {})
    if top:
        elements.append(Paragraph(
            f"<b>Top Prediction:</b> {top.get('disease', '?')} "
            f"({top.get('probability', 0) * 100:.1f}% — {top.get('status', '').replace('_', ' ').title()})",
            styles["Normal"],
        ))
        elements.append(Spacer(1, 4 * mm))

    # 7. Grad-CAM Heatmap
    gradcam = prediction_data.get("gradcam", {})
    if gradcam and gradcam.get("image"):
        try:
            gc_b64 = gradcam["image"]
            if "," in gc_b64:
                gc_b64 = gc_b64.split(",", 1)[1]
            gc_bytes = base64.b64decode(gc_b64)
            gc_buffer = io.BytesIO(gc_bytes)
            elements.append(Paragraph("Grad-CAM Heatmap", heading_style))
            elements.append(Paragraph(
                f"Model: {gradcam.get('model_used', 'Unknown')} — "
                "Highlighted regions show areas the model focused on during prediction.",
                styles["Normal"],
            ))
            elements.append(RLImage(gc_buffer, width=120 * mm, height=90 * mm, kind="proportional"))
            elements.append(Spacer(1, 4 * mm))
        except Exception as e:
            logger.warning(f"Could not embed Grad-CAM in PDF: {e}")

    # 8. Footer
    elements.append(Spacer(1, 8 * mm))
    elements.append(Paragraph(
        "Generated by Healthcare DL System — For educational purposes only.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=HexColor("#94a3b8")),
    ))

    doc.build(elements)
    return buffer.getvalue()
